### ISSUE TITLE
parallel versions of a text

### ISSUE THREAD

**Issue by PietroLiuzzo** [evt-project/evt-viewer#11]
We have a text with more then one version, in Classical ethiopic and in latin, which is edited in one TEI file, using different divs for the editions and relative translations.

It would be nice to be able to see in parallel these versions, with their apparata, so that it is clear the relation between the two texts and the relation of each translation of its source.

Thank you

**Comment by ChiaraMartignano** [comment]
Dear Pietro,
thank you for submitting this issue. Actually we have opened already an issue on this very same same topic ( #10 ). I'm closing this one because it is a duplicate, but please join us in the discussion of issue #10!
