### ISSUE TITLE
warning on install time

### ISSUE THREAD

**Issue by luigiusai** [evt-project/evt-viewer#2]
Dear programmers,
some seconds ago I was installing your amazing tool to test it on localhost.
I had this message:

C:\Ruby24-x64\bin>npm install -g bower
npm WARN deprecated bower@1.8.2: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
C:\Users\Gigi\AppData\Roaming\npm\bower -> C:\Users\Gigi\AppData\Roaming\npm\node_modules\bower\bin\bower
+ bower@1.8.2
added 1 package in 64.826s

C:\Ruby24-x64\bin>

I hope this message could be useful, to you all.
Best regards

**Comment by ChiaraMartignano** [comment]
Thank you for the warning and for your appreciation!
In the next future we are going to migrate EVT 2.0 from AngularJS to Angular2+. So we'll have the chance to change the framework and work with state-of-the-art technologies. By then we'll keep an eye on the status of Bower.
