### ISSUE TITLE
evt hosting question

### ISSUE THREAD

**Issue by nafergo** [evt-project/evt-viewer#34]
Is it possible to run an evt intance on gh-pages?

**Comment by RobertoRDT** [comment]
Hello nafergo, not yet with AngularJS, as far as I know. We're interested in this, but it may well be that it will have to wait until the port to Angular 8 is under way to be implemented. If you have more information / examples of tools doing that feel free to copy that here.

**Comment by RobertoRDT** [comment]
Hi @nafergo apparently I was wrong: https://evt-project.github.io/evt-demo/

@szenzaro managed to do it with the current pre-beta2 version of EVT, still based on AngularJS.

**Comment by federicaspinelli** [comment]
Passages required:
1. create a build of evt including configuration and edition data
2. enter the data on a github repository
3. enable githubpages for this repository (they must point to the right branch)
4. verify that the githubpages address of the repository works correctly

To view an example and settings see this repository: https://github.com/evt-project/evt-demo. 
And its "publication": https://evt-project.github.io/evt-demo:
