### ISSUE TITLE
Paragraphs inside of quote elements don't get highlighted properly

### ISSUE THREAD

**Issue by ChiaraMartignano** [evt-project/evt-viewer#4]
Paragraphs inside of quote elements don't get highlighted with the same highlighting color of the other contents of the quote.
See sample file:
![image](https://user-images.githubusercontent.com/23243170/46539301-693cde80-c8b6-11e8-8c72-4a0168cb610b.png)

**Comment by federicaspinelli** [comment]
Problem solved in Beta1, see sample file: 
<img width="845" alt="Schermata 2020-04-27 alle 12 55 04" src="https://user-images.githubusercontent.com/26044952/80364537-659cee00-8886-11ea-9c66-bc53a7a2455d.png">

Find a new bug, relate to <quote> inside <p> without other element, see sample file: 
<img width="842" alt="Schermata 2020-04-27 alle 12 52 57" src="https://user-images.githubusercontent.com/26044952/80364844-e0fe9f80-8886-11ea-8327-18c8c94b6833.png">

Correct visualization if <quote> its inside <app> and <lem> elements, see sample file:
<img width="790" alt="Schermata 2020-04-27 alle 13 12 51" src="https://user-images.githubusercontent.com/26044952/80366021-d6dda080-8888-11ea-9e41-e8b673ad654e.png">

**Comment by federicaspinelli** [comment]
Close in [75](https://github.com/evt-project/evt-viewer/pull/75)

**Comment by federicaspinelli** [comment]
Close in https://github.com/evt-project/evt-viewer/pull/75.
