### ISSUE TITLE
Diplomatic edition features not visualized [Ars Breviata]

### ISSUE THREAD

**Issue by RobertoRDT** [evt-project/evt-viewer#55]
In the 20200110 build the basic diplomatic edition features (abbreviations, normalisations) don't work when loading the Ars Breviata edition files (hereby attached). This is a regression because they worked fine in the previous (20191217) build.

[ars_breviata.zip](https://github.com/evt-project/evt-viewer/files/4159205/ars_breviata.zip)

![Screenshot (21)](https://user-images.githubusercontent.com/16621283/73838002-fa0d2c80-4812-11ea-81be-7dd690b85218.png)

**Comment by RobertoRDT** [comment]
After a quick check with the DOTR, text normalizations aren't displayed but abbreviations are.
![immagine](https://user-images.githubusercontent.com/16621283/73838201-6daf3980-4813-11ea-97a0-5d9f9ede2dee.png)

**Comment by RobertoRDT** [comment]
A possible problem with the Ars Breviata text is that the <g> elements link to <charDecl> elements that do not exist (yet).

**Comment by federicaspinelli** [comment]
Text normalizations and abbreviations are now displayed
<img width="1680" alt="Schermata 2020-02-18 alle 12 01 14" src="https://user-images.githubusercontent.com/26044952/75147921-b6655e80-56fe-11ea-8971-46810d9f4dcb.png">
