### ISSUE TITLE
Text not loaded at program start [Ars Breviata]

### ISSUE THREAD

**Issue by RobertoRDT** [evt-project/evt-viewer#56]
At the first loading of the TEI files for the Ars Breviata edition (see https://github.com/evt-project/evt-viewer/issues/54 for the actual files) EVT fails to load and show the text, it usually works after the page is refreshed though. It can happen with the DOTR too, but much less frequently.

![immagine](https://user-images.githubusercontent.com/16621283/73838415-e9a98180-4813-11ea-86f8-f6b803160727.png)

**Comment by federicaspinelli** [comment]
Fix bug with sources loading. Merged #68 into develop.
