### ISSUE TITLE
Missing spaces between readings (especially add and del elements)

### ISSUE THREAD

**Issue by ChiaraMartignano** [evt-project/evt-viewer#6]
There is no space between some readings (especially add and del), so that it makes it more difficult to read.
See sample:
![spaces_bug](https://user-images.githubusercontent.com/23243170/46541685-f7b45e80-c8bc-11e8-9185-6c25e7d52daf.PNG)

**Comment by federicaspinelli** [comment]
Solved.
<img width="853" alt="Schermata 2020-04-27 alle 11 59 16" src="https://user-images.githubusercontent.com/26044952/80359745-8feaad80-887e-11ea-8929-3cfca174268f.png">
