### ISSUE TITLE
Pin icon is rotated when pinned box is opened

### ISSUE THREAD

**Issue by ChiaraDipi** [evt-project/evt-viewer#79]
When pinned box is opened, the icon is rotated 180deg:
<img width="419" alt="Schermata 2020-05-11 alle 17 53 19" src="https://user-images.githubusercontent.com/7116412/81582587-839f3e00-93b0-11ea-9f1c-8b948a091dda.png">

It is probably because the item is given the class `left` which has a CSS rule `transform(rotate(180deg))`. Either move the rotate rule to a more specific class o disable rotation for pin box toggle button.

**Comment by federicaspinelli** [comment]
<img width="1680" alt="Schermata 2020-05-15 alle 12 58 19" src="https://user-images.githubusercontent.com/26044952/82043371-c2ccd800-96ab-11ea-9bc7-6714f5e07480.png">
